{% set name = "rapidjson" %}
{% set version = "1.1.0" %}
{% set sha256 = "bf7ced29704a1e696fbccf2a2b4ea068e7774fa37f6d7dd4039d0787f8bed98e" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/miloyip/rapidjson/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0

requirements:
  build:
    - cmake  {{ cmake }}
    - {{ compiler('cxx') }}
    - make  {{ make }}  # [unix]

test:
  commands:
    - test -f ${PREFIX}/include/rapidjson/rapidjson.h                     # [unix]
    - test -f ${PREFIX}/lib/cmake/RapidJSON/RapidJSONConfig.cmake         # [unix]
    - test -f ${PREFIX}/lib/cmake/RapidJSON/RapidJSONConfigVersion.cmake  # [unix]
    - if exist %LIBRARY_PREFIX%\include\rapidjson\rapidjson.h (exit 0) else (exit 1)                     # [win]
    - if exist %LIBRARY_PREFIX%\lib\cmake\RapidJSON\RapidJSONConfig.cmake (exit 0) else (exit 1)         # [win]
    - if exist %LIBRARY_PREFIX%\lib\cmake\RapidJSON\RapidJSONConfigVersion.cmake (exit 0) else (exit 1)  # [win]

about:
  home: http://rapidjson.org/
  summary: A fast JSON parser/generator for C++ with both SAX/DOM style API
  license: MIT
  license_file: license.txt
  license_family: MIT
  summary: A fast JSON parser/generator for C++ with both SAX/DOM style API
  dev_url: https://github.com/miloyip/rapidjson
  doc_url: http://rapidjson.org/
  doc_source_url: https://github.com/miloyip/rapidjson/tree/master/doc
  description: |
    RapidJSON is a self-contained and header only parser/generator for C++, which
    supports both SAX and DOM style API, with no external dependencies such as
    BOOST. It uses a fast memory allocator, and the parser allocates memory
    compactly during parsing. It supports UTF-8, UTF-16, UTF-32 (LE & BE), and
    their detection, validation and transcoding internally. It should be fully in
    compliance with RFC7159/ECMA-404, with optional support of relaxed syntax.

extra:
  recipe-maintainers:
    - open-ce/open-ce-dev-team
